/* Workbench — shared parts for browser-based maker tools.
 * Copyright (C) 2026 shahidhussain2k13@gmail.com
 * SPDX-License-Identifier: GPL-3.0-or-later — see LICENSE. */
/* build.mjs — joins src/ into dist/workbench.js and css/ into
 * dist/workbench.css. No transpiling: the sources are classic scripts, so the
 * bundle is them in order, stamped with the version. */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

// Load order matters: base first, then what builds on it.
export const JS = ['base.js', 'fonts.js', 'edt.js', 'contour.js', 'shapes.js', 'zip.js',
                   'decor.js', 'export.js', 'share.js', 'drawpad.js', 'ui.js'];
export const CSS = ['workbench.css'];

const stamp = `/* Workbench ${pkg.version} — https://github.com/ShahidHussain-srti/workbench\n` +
  ` * Copyright (C) 2026 shahidhussain2k13@gmail.com\n` +
  ` * SPDX-License-Identifier: GPL-3.0-or-later. Generated by tools/build.mjs; edit src/ instead. */\n`;

function join_(dir, files) {
  return files.map(f => {
    let p = join(root, dir, f);
    let s;
    try { s = readFileSync(p, 'utf8'); } catch { return ''; }
    return `\n/* ── ${f} ── */\n` + s;
  }).join('');
}

mkdirSync(join(root, 'dist'), { recursive: true });
writeFileSync(join(root, 'dist/workbench.js'), stamp + `window.WB = window.WB || {};\nwindow.WB.version = '${pkg.version}';\n` + join_('src', JS));
writeFileSync(join(root, 'dist/workbench.css'), stamp + join_('css', CSS));
console.log('built dist/workbench.js and dist/workbench.css', pkg.version);
